import AppKit
import Foundation
import UniformTypeIdentifiers

enum ExportFormat: String, CaseIterable {
    case markdown
    case json
    case swift
    case plainText

    var utType: UTType {
        switch self {
        case .markdown: .init(filenameExtension: "md")!
        case .json: .json
        case .swift: .swiftSource
        case .plainText: .plainText
        }
    }

    var fileExtension: String {
        switch self {
        case .markdown: "md"
        case .json: "json"
        case .swift: "swift"
        case .plainText: "txt"
        }
    }
}

@MainActor
enum ExportService {
    static func exportChat(messages: [ChatMessage]) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.init(filenameExtension: "md")!, .json, .plainText]
        panel.nameFieldStringValue = "chat-export.md"
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }

            let ext = url.pathExtension
            let content: String

            if ext == "json" {
                let encoder = JSONEncoder()
                encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
                if let data = try? encoder.encode(messages),
                   let json = String(data: data, encoding: .utf8) {
                    content = json
                } else {
                    content = "[]"
                }
            } else if ext == "md" {
                content = messages.map { msg in
                    let role = msg.role.rawValue.uppercased()
                    return "### \(role)\n\n\(msg.content)\n"
                }.joined(separator: "\n---\n\n")
            } else {
                content = messages.map { msg in
                    "\(msg.role.rawValue.uppercased()): \(msg.content)"
                }.joined(separator: "\n\n")
            }

            try? content.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    static func exportSchema(_ schema: SchemaDefinition) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.swiftSource]
        panel.nameFieldStringValue = "\(schema.name).swift"
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            try? schema.swiftCode.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    static func exportModelInfo(availability: String, tokensPerSecond: Double) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.init(filenameExtension: "md")!]
        panel.nameFieldStringValue = "model-info.md"
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            let content = """
            # Think Locally — Model Report

            - **Status**: \(availability)
            - **Parameters**: ~3B
            - **Context Window**: 4,096 tokens
            - **Throughput**: \(String(format: "%.1f", tokensPerSecond)) tok/s
            - **Framework**: FoundationModels (Apple Intelligence)
            - **Execution**: 100% on-device, Neural Engine

            Generated by Think Locally.
            """
            try? content.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    static func copyToClipboard(_ text: String) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
    }
}
